### ISSUE TITLE
 Please add description.

### ISSUE THREAD

**Issue by priyankarpal** [thecocode/blog-a-thon#2]
**I noticed that there is no description in this repository. So please add a description.** 

![Screenshot from 2023-01-21 23-56-52](https://user-images.githubusercontent.com/88102392/213881655-a2fe6d04-1d3f-4881-a571-fb2e226cf38e.png)

**Comment by shubhxg** [comment]
I also noticed this. 👍 Thanks for the mention of this.

**Comment by poojasanwal** [comment]
Thanks for bringing this to my notice, @priyankarpal and @shubhsharma19. Doing as suggested!
