### ISSUE TITLE
README.md recreated  🧑‍💻

### ISSUE THREAD

**Issue by priyankarpal** [thecocode/blog-a-thon#3]
# Heyy developers, after checking `README.md` I recreated a `README.md` for this community. Hope it will help

# 👉 Before
![1](https://user-images.githubusercontent.com/88102392/213883188-5ae76c5f-06b1-40ad-9fdc-495a528d5c75.png)
![2](https://user-images.githubusercontent.com/88102392/213883190-6aa75f72-b688-42dc-8af2-f373dbd8cbf3.png)
![3](https://user-images.githubusercontent.com/88102392/213883192-3247f40c-08a5-477a-a7ec-a7959e47b1ae.png)

# 👉 After
![Screenshot from 2023-01-22 00-34-50](https://user-images.githubusercontent.com/88102392/213883095-8d147317-2ed0-413d-bc45-78a83cd6c3dd.png)
![Screenshot from 2023-01-22 00-34-58](https://user-images.githubusercontent.com/88102392/213883094-5abc2385-99fc-4ec0-9e65-4773cfff9cbb.png)
![Screenshot from 2023-01-22 00-35-13](https://user-images.githubusercontent.com/88102392/213883090-16facdd0-f973-442a-b18c-469c7f5cf475.png)

**Comment by poojasanwal** [comment]
Thanks for your contribution, @priyankarpal. I have merged your PR!
